### ISSUE TITLE
received "Missing Subscribe Key" in console

### ISSUE THREAD

**Issue by yingqiaogit** [pubnub/pubnub-rickshaw-memory#1]
I installed the library, and added the code in my app.js as follows 

var memoryMonitor = require('pubnub-rickshaw-memory');

//memoryMonitor.init({dev:true});

memoryMonitor.init({publish_key: 'demo',
    channel: 'mytest',
    interval_timeout: 1000,
    dev: true,
    port: 3333});

The console displays the following messages intermittently while my app is running
Missing Subscribe Key
Missing Subscribe Key
....

Any suggestion?

**Comment by ytkang** [comment]
I got same error

**Comment by jpetitcolas** [comment]
Same here. :(

**Comment by igor-galchevsky** [comment]
Same error

**Comment by rzachariah** [comment]
I'm getting this too. So what's the deal here?

**Comment by rzachariah** [comment]
Perhaps all we need is to supply the subscribe_key to pubnub.init?

// init pubnub
var pubnub = require("pubnub")({
  publish_key: publish_key
});

**Comment by mitchellporter** [comment]
I was able to fix this issue by changing my `publish_key` and `subscribe_key` params used in my pubnub init object to `publishKey` and `subscribeKey`.

**Comment by ianjennings** [comment]
Resolved in #4

**Comment by guruprasad211** [comment]
i am getting the same error how to resolve this
